// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd7vHRQwQyuu4VF9EomltWZ3Zx-rN-2XY',
    appId: '1:218941956601:web:bbff198a90ce96eca35d28',
    messagingSenderId: '218941956601',
    projectId: 'qr-app-fd418',
    authDomain: 'qr-app-fd418.firebaseapp.com',
    storageBucket: 'qr-app-fd418.appspot.com',
    measurementId: 'G-BGN3CMX3EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqdYxr63mvP4kVcvks5KMNOosy_rWyJc',
    appId: '1:218941956601:android:97ee529640af1b38a35d28',
    messagingSenderId: '218941956601',
    projectId: 'qr-app-fd418',
    storageBucket: 'qr-app-fd418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPraQvPGGtwwRA1zlX7buEJPQZ1VVLDY',
    appId: '1:218941956601:ios:33094f1dc869e337a35d28',
    messagingSenderId: '218941956601',
    projectId: 'qr-app-fd418',
    storageBucket: 'qr-app-fd418.appspot.com',
    iosClientId: '218941956601-lv6q79rr0skhqqq97hefk774nicn7g67.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPraQvPGGtwwRA1zlX7buEJPQZ1VVLDY',
    appId: '1:218941956601:ios:33094f1dc869e337a35d28',
    messagingSenderId: '218941956601',
    projectId: 'qr-app-fd418',
    storageBucket: 'qr-app-fd418.appspot.com',
    iosClientId: '218941956601-lv6q79rr0skhqqq97hefk774nicn7g67.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrApp',
  );
}
